version: 2.1
orbs:
  # aws-cli orb is unused, removing it
  aws-cli: circleci/aws-cli@4.1.2
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  update_file:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - aws-s3/sync:
          bucket: 
          local-dir: C:\Users\NAVEEN\OneDrive\Desktop\text\frontend
          overwrite: true
          key-prefix: path/to/file.txt    



# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.6-jessie-browsers
#     steps:
#       - checkout
#       - run:
#           name: Install AWS CLI command
#           command: pip install awscli
#       - run:
#           name: Configure AWS credentials command
#           command: |
#             aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
#             aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
#             aws configure set region ${AWS_DEFAULT_REGION}
#       - run:
#           name: Sync to S3 command
#           command: aws s3 sync ~/project s3://mybucket --delete
